### PR TITLE
Json

### PR DESCRIPTION
**Pull request by kbairak**
TODOs:

- [x] Decide whether to use `DumbJson` or the official `json` module
- [x] Clean up some leftover code
- [x] Escape keys
- [x] Return helpful `ParseError`s when things go wrong
- [x] Use official `json` module to do a first pass
- [x] check for JSON values that aren't only arrays, dicts or strings (make sure booleans, nulls, dates etc are handled properly)
- [x] See if we have to take care of case where root JSON element is not dict
- [x] Write tests

@tabac @ollandos @SofiaMargariti @kouk I need your help in deciding the first point

pros of `DumbJson`:
- It allows us to preserve indentation and raw (escaped) source strings

cons of `DumbJson`:
- It's handwritten, not official.

@tabac @ollandos If you're up for an early review (although there's still work left to do), feel free.

### CODE REVIEW

**Comment by kbairak** [comment]
I'm going with the `DumbJson` option until given compelling reason not to.

**Comment by kouk** [comment]
@kbairak +1 for dumbjson. Although tbh I would prefer if it was separated from the actual handler code. Like a separate library project.

**Comment by kbairak** [comment]
@kouk:

The coverage falling makes sense considering there's a new handler with no tests. I will write them.

It is a separate library, it is on `utils/json.py`

**Comment by kouk** [comment]
@kbairak right you are. I got confused with the `JsonHandler_` code still being in there.

**Comment by kbairak** [comment]
I think this is done. Anybody wants to review?

**Pull request merged**
