### PR TITLE
Github markdown file format support

### PR DESCRIPTION
**Pull request by diegobz**

### CODE REVIEW

**Comment by kbairak** [comment]
@diegobz try putting that sample file in the proper place in order to auto-generate some tests and have the testbed pre-load it.

http://openformats.readthedocs.io/en/latest/testing.html#get-yourself-a-sample-file

**Comment by kbairak** [comment]
@diegobz nice, btw. I'll check it out

**Comment by diegobz** [comment]
@kbairak Done!

**Comment by kbairak** [comment]
I will merge this, but please make sure that, after the demo, we delete the resources created and work thoroughly on the format before putting it into production. Because few people understand it and there are not sufficient tests, I wouldn't say it's production ready and I wouldn't want to introduce second versions that early.

**Pull request merged**
